### ISSUE TITLE
Ticket System

### ISSUE THREAD

**Issue by zazikii** [littxle/Coding-kekes#1]
Ich wollte dein Ticketsystem verwenden, hatte aber zunächst ein paar Probleme. Es wird keine Datenbank erstellt, wenn der ein / in seinem Namen enthält, und wenn ich es entferne, wird eine erstellt, aber wenn ich den Befehl verwende, wird angezeigt, dass es keine solche Tabelle gibt: Ticket

**Comment by Nico4devv** [comment]
### _

> [Herzlichen Dank für Ihre Aufmerksamkeit und die Meldung des Fehlers. Ihre Hinweise sind äußerst wertvoll für uns, um unsere Dienste zu verbessern. Ich möchte Ihnen versichern, dass ich persönlich dafür sorgen werde, dass das Problem umgangen wird, sobald ich wieder an meinen Arbeitsplatz bin. Ihre Unterstützung trägt maßgeblich dazu bei, die Qualität unserer Arbeit zu sichern. Nochmals vielen Dank für Ihre Hilfe und Geduld

_

**Comment by Nico4devv** [comment]
> ### _
> > [Herzlichen Dank für Ihre Aufmerksamkeit und die Meldung des Fehlers. Ihre Hinweise sind äußerst wertvoll für uns, um unsere Dienste zu verbessern. Ich möchte Ihnen versichern, dass ich persönlich dafür sorgen werde, dass das Problem umgangen wird, sobald ich wieder an meinen Arbeitsplatz bin. Ihre Unterstützung trägt maßgeblich dazu bei, die Qualität unserer Arbeit zu sichern. Nochmals vielen Dank für Ihre Hilfe und Geduld
> 
> _
the bug bald gefix

**Comment by zazikii** [comment]
Danke!

**Comment by Nico4devv** [comment]
Hallo,

ich wollte mich noch einmal bei Ihnen melden. Ich hoffe, dass der behobene Bug nun keine Probleme mehr verursacht. Soweit ich sehen konnte, habe ich alles behoben, was möglich war. Falls jedoch weiterhin Schwierigkeiten auftreten sollten, bitte ich Sie, ein neues Ticket zu öffnen.

Vielen Dank und beste Grüße!
