### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by RealHighfx** [littxle/Coding-kekes#2]
Hey, ich wollte fragen ob mor jemand bei einen Bug helfen kann da der "Noch Fragen, Add User, delete User" nicht funktioniert

**Comment by Nico4devv** [comment]
_```
**Hallo lieber Real Highflex,

ich hoffe, es geht dir gut! Ich wollte dich nur kurz daran erinnern, dass du mir bitte noch die Bilder und weitere Informationen zukommen lassen solltest. Es wäre wirklich super, wenn du das so bald wie möglich erledigen könntest.

Außerdem, falls du eine bestimmte Rolle oder Position im Zusammenhang mit unserem Projekt angegeben hast, wäre es hilfreich, wenn du mir das ebenfalls mitteilen könntest. Je mehr Details ich habe, desto besser kann ich mich darauf vorbereiten und sicherstellen, dass wir alle Anforderungen erfüllen.

Ich bin sehr gespannt darauf, mit dir zusammenzuarbeiten und bin sicher, dass wir gemeinsam großartige Ergebnisse erzielen können. Falls du irgendwelche Fragen hast oder weitere Informationen benötigst, zögere bitte nicht, mich zu kontaktieren.

Vielen Dank im Voraus für deine Unterstützung!

Herzliche Grüße,
Jinxex**
```_

**Comment by RealHighfx** [comment]
Ja die Rolle wurde geaddet aber diese Fehler 
![Screenshot_20240513-123834_Discord](https://github.com/Jinxex/Coding-kekes/assets/157031896/bafa0a67-0d47-47f7-8f77-8d7f3ca112c8)
![Screenshot_20240513-123802_Discord](https://github.com/Jinxex/Coding-kekes/assets/157031896/c85602b5-15e9-4051-a782-1f1864e9f833)
![Screenshot_20240513-123709_Discord](https://github.com/Jinxex/Coding-kekes/assets/157031896/605b19df-1f17-4f92-bca6-849a7cd4c6c1)
![Screenshot_20240513-123649_Discord](https://github.com/Jinxex/Coding-kekes/assets/157031896/6b46e2cb-2529-4708-a36c-1d0de4356a12)

**Comment by RealHighfx** [comment]
Und es word nicht immer das deletete ticket in die logs gespeichert

**Comment by Nico4devv** [comment]
du hast keine role XD

**Comment by RealHighfx** [comment]
Doch habe ich eigentlich schon

**Comment by RealHighfx** [comment]
Was kann ich machen damit der Fehler nd mehr kommt

**Comment by Nico4devv** [comment]
es muss so aussehen 
![image](https://github.com/Jinxex/Coding-kekes/assets/117511417/a08bfc8c-28da-4ca8-a51e-b99fdfefbfb9)
und denn  
![image](https://github.com/Jinxex/Coding-kekes/assets/117511417/d70bfe59-e69f-47ab-9d60-165edca75714)
 und 
![image](https://github.com/Jinxex/Coding-kekes/assets/117511417/3571d7ea-bc70-4447-86fb-5f9448b9a8a2)
 kannst du es acuh machen

**Comment by RealHighfx** [comment]
Tut es und die Rolle is ja da

**Comment by Nico4devv** [comment]
denn send mal das bro

**Comment by RealHighfx** [comment]
Ganz unten
![Screenshot_20240513-134211_Discord](https://github.com/Jinxex/Coding-kekes/assets/157031896/a55dbeef-af17-4b6b-9182-131b9bcbedb5)

**Comment by Jinxex** [comment]
lost oder so

**Comment by Jinxex** [comment]
Ich werde das jetzt schließen, da ich deine Fehlermeldung nicht verstehe. Zweitens, es wäre hilfreich, wenn du weitere Details bereitstellen könntest, um das Problem besser zu verstehen. Bitte gib mir Bescheid, wenn du Hilfe benötigst

**Comment by Nico4devv** [comment]
**Ich werde das jetzt schließen, da ich deine Fehlermeldung nicht verstehe. Zweitens, es wäre hilfreich, wenn du weitere Details bereitstellen könntest, um das Problem besser zu verstehen. Bitte gib mir Bescheid, wenn du Hilfe benötigst** 


lg ; code owner
