### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by RealHighfx** [littxle/Coding-kekes#4]
Hey ich habe einen Bug, dass ich bei dem Ticket System wenn der log channel auf 2 Servern gleich heißt speichert er trotzdem nur eines und vom 2. Server gar nichts (transcript)

**Comment by Nico4devv** [comment]
Dies kann nicht möglich sein, da es über eine ID läuft. Die ID kann nicht für jeden Server gleich sein

**Comment by RealHighfx** [comment]
Jetzt ist gerade das Problem es kommen in gar keinen channel die transcripts

**Comment by Nico4devv** [comment]
Hm wie gesagt das ist wegen dir und nicht wegen dem code aber okay lösch doch mal die db lad dir noch mal runter

**Comment by RealHighfx** [comment]
ok

**Comment by RealHighfx** [comment]
Kannst du mir vllt deinen code senden den du gerade drinnen hast weil bei mir wird nicht immer da transkript gesendet
